/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Acceuil: typeof import('./src/components/Acceuil.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    copy: typeof import('./src/components/InfosPratiques copy.vue')['default']
    Equipes: typeof import('./src/components/Equipes.vue')['default']
    InfosPratiques: typeof import('./src/components/InfosPratiques.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Joueurs: typeof import('./src/components/Joueurs.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
